[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'Shougo/unite.vim'

[[plugins]]
repo = 'Shougo/vimfiler.vim'

[[plugins]]
repo = 'davidhalter/jedi-vim'

[[plugins]]
repo = 'Yggdroot/indentLine'

[[plugins]]
repo = 'zchee/deoplete-jedi'

[[plugins]]
repo = 'vim-airline/vim-airline'

[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'jacoborus/tender.vim'

[[plugins]]
repo = 'rhysd/vim-color-spring-night'

[[plugins]]
repo = 'tomasr/molokai'

[[plugins]]
repo = 'ctrlpvim/ctrlp.vim'

[[plugins]]
repo = 'nvie/vim-flake8'

[[plugins]]
repo = 'vim-scripts/rdark'

[[plugins]]
repo = 'pangloss/vim-javascript'

[[plugins]]
repo = 'zchee/deoplete-clang'
hook_source = '''
let g:deoplete#sources#clang#libclang_path = '/Library/Developer/CommandLineTools/usr/lib/libclang.dylib'
let g:deoplete#sources#clang#clang_header = '/Library/Developer/CommandLineTools/usr/lib/clang'
'''

on_ft = ['c', 'cpp', 'cmake']
depends = ['deoplete.nvim']

[[plugins]]
repo = 'rakr/vim-one'

[[plugins]]
repo = 'tpope/vim-vividchalk'

[[plugins]]
repo = 'mhinz/vim-startify'

[[plugins]]
repo = 'w0rp/ale'

[[plugins]]
repo = 'agude/vim-eldar'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'bronson/vim-trailing-whitespace'

[[plugins]]
repo = 'roxma/nvim-yarp'

[[plugins]]
repo = 'roxma/vim-hug-neovim-rpc'
